version: '3.8'

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: blogdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - blog-network

  blog-app:
    build: .
    container_name: blog-app
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_NAME: blogdb
      DB_USER: root
      DB_PASSWORD: root
    networks:
      - blog-network

volumes:
  mysql-data:

networks:
  blog-network:

